### PR TITLE
TUN-8140: Deprecate cloudflared and disable warp from cloudflare-homebrew

### LINKED ISSUE #9: cloudflared 2019.9.0 -> 2019.9.2
==> Upgrading 1 outdated package:
cloudflare/cloudflare/cloudflared 2019.9.0 -> 2019.9.2
==> Upgrading cloudflare/cloudflare/cloudflared
rm /usr/local/bin/cloudflared
ln -s ../Cellar/cloudflared/2019.9.0/bin/cloudflared cloudflared
Error: The following formula
  cloudflared
cannot be installed as binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install
  
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
$ xcode-select --version
xcode-select version 2370.

### LINKED ISSUE #13: cloudflare-warp-bot broken?
Where is 2020.2.1?

### LINKED ISSUE #14: cloudflared out of date
The `cloudflared` in this Homebrew repo is `2020.2.0`, but the current version is `2020.3.2`

Please update

### LINKED ISSUE #30: Warp should be removed
The build that is linked in `warp.rb` is from 2018. The installation instructions are very different now: https://developers.cloudflare.com/warp-client/setting-up/macOS & https://developers.cloudflare.com/warp-client/setting-up/linux.

### LINKED ISSUE #74: cloudflared formula is out of date and doesn't provide arm64 binary
The current version is 2023.8.2 while the latest release is 2023.10.0 as of writing.
Also that the URL points to amd64 binary only while an arm64 build is available. The formula should check `Hardware::CPU.arm?`

https://github.com/cloudflare/homebrew-cloudflare/blob/bb542982cb5f6e5261c73df95e6b2122ab545733/cloudflared.rb#L4

### PR DESCRIPTION
**Pull request by jcsf**
## Summary
The tunnel team decided that the homebrew-core will be the official repository
for cloudflared and therefore, the artifact on this repository will be deprecated
and afterwards disabled.

Closes #74 
Closes #30
Closes #14 
Closes #13 
Closes #9

### CODE REVIEW

File: warp.rb [hunk 1]
```diff
@@ -1,4 +1,5 @@
 class Warp < Formula
+  disable! date: "2024-01-10", because: ":unmaintained"
```
Comment (DevinCarr) [inline warp.rb:2]: The default provided reasons don't need quotes.
```suggestion
  disable! date: "2024-01-10", because: :unmaintained
```

File: cloudflared.rb [hunk 2]
```diff
@@ -1,4 +1,5 @@
 class Cloudflared < Formula
+  disable! date: "2024-01-10", because: "moved to homebrew-core repository"
```
Comment (DevinCarr) [inline cloudflared.rb:2]: Let's favor deprecate for cloudflared since the package is still valid and working. In a year we can remove it.
```suggestion
  deprecate! date: "2024-01-10", because: "moved to homebrew-core repository"
  disable! date: "2025-01-10", because: "moved to homebrew-core repository"
```

**Review by jacobbednarz — APPROVED** [review]

**Review by chungthuang — APPROVED** [review]
